### ISSUE TITLE
saldos mercadorias

### ISSUE THREAD

**Issue by lnoering** [Varejonline/api#1]
- Ao setar a '&entidades=1' e '&inicio=X&quantidade=500' não me retornou todos os produtos da entidade. (X incrementando 500) 
- Passei a setar '&quantidade=300' e passou a funcionar. (X incrementando 300)

**Comment by marcoskapp** [comment]
Caso Desenvolvedor, 

Nosso limite de paginação foi reduzido para 300 registros, conforme documentação em: https://github.com/Varejonline/api/wiki/Pagina%C3%A7%C3%A3o%20de%20resultados

Quanto ao funcionamento da API de saldos de mercadorias, são retornados apenas registros que possuam movimentação na entidade filtrada.

Att,
